[2024-10-02T17:26:15.487+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:26:15.516+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-10-02T17:26:15.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-10-02T17:26:15.528+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:26:15.780+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-28 00:00:00+00:00
[2024-10-02T17:26:15.788+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1542) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:26:15.790+0000] {standard_task_runner.py:63} INFO - Started process 1564 to run task
[2024-10-02T17:26:15.790+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpg9713jzt']
[2024-10-02T17:26:15.794+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask transformar
[2024-10-02T17:26:15.856+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:26:15.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-10-02T17:26:15.960+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:26:16.158+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:26:16.159+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in transformar
    df_agrupada = df.groupby('ContinentExp')[['cases', 'deaths']].sum().reset_index()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'ContinentExp'
[2024-10-02T17:26:16.177+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-28T00:00:00+00:00, execution_date=20231128T000000, start_date=20241002T172615, end_date=20241002T172616
[2024-10-02T17:26:16.194+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 128 for task transformar ('ContinentExp'; 1564)
[2024-10-02T17:26:16.247+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:26:16.274+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:26:16.280+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:58:22.232+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:58:22.301+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-10-02T18:58:22.732+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-10-02T18:58:22.733+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:58:22.911+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-28 00:00:00+00:00
[2024-10-02T18:58:22.925+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5788) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:58:22.928+0000] {standard_task_runner.py:63} INFO - Started process 5816 to run task
[2024-10-02T18:58:22.928+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '1150', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpbwxu7qkq']
[2024-10-02T18:58:22.932+0000] {standard_task_runner.py:91} INFO - Job 1150: Subtask transformar
[2024-10-02T18:58:23.024+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:58:23.224+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-10-02T18:58:23.228+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:58:23.524+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:58:23.525+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:58:23.532+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-28T00:00:00+00:00, execution_date=20231128T000000, start_date=20241002T185822, end_date=20241002T185823
[2024-10-02T18:58:23.597+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:58:23.617+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:58:23.619+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:24:31.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:24:31.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-10-02T19:24:31.516+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-10-02T19:24:31.517+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:24:31.539+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-28 00:00:00+00:00
[2024-10-02T19:24:31.547+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:24:31.548+0000] {standard_task_runner.py:63} INFO - Started process 9146 to run task
[2024-10-02T19:24:31.548+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '2148', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpww11zu6e']
[2024-10-02T19:24:31.553+0000] {standard_task_runner.py:91} INFO - Job 2148: Subtask transformar
[2024-10-02T19:24:31.608+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-28T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:24:31.713+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-10-02T19:24:31.717+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:24:31.939+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:24:31.940+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:24:31.956+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-28T00:00:00+00:00, execution_date=20231128T000000, start_date=20241002T192431, end_date=20241002T192431
[2024-10-02T19:24:32.006+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:24:32.029+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:24:32.032+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
