[2024-10-02T17:26:53.908+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:26:53.938+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [queued]>
[2024-10-02T17:26:53.945+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [queued]>
[2024-10-02T17:26:53.946+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:26:54.155+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-10 00:00:00+00:00
[2024-10-02T17:26:54.162+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1758) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:26:54.164+0000] {standard_task_runner.py:63} INFO - Started process 1774 to run task
[2024-10-02T17:26:54.163+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-10T00:00:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpa8thfidd']
[2024-10-02T17:26:54.165+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask extrair
[2024-10-02T17:26:54.217+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:26:54.296+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-10T00:00:00+00:00'
[2024-10-02T17:26:54.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:27:00.301+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:27:00.302+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in extrair
    df.to_csv('data/dados_covid_extraidos.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'
[2024-10-02T17:27:00.319+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-10T00:00:00+00:00, execution_date=20240110T000000, start_date=20241002T172653, end_date=20241002T172700
[2024-10-02T17:27:00.466+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 197 for task extrair ([Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'; 1774)
[2024-10-02T17:27:00.513+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:27:00.545+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:27:00.560+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:59:03.881+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:59:03.911+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [queued]>
[2024-10-02T18:59:04.145+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [queued]>
[2024-10-02T18:59:04.145+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:59:04.222+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-10 00:00:00+00:00
[2024-10-02T18:59:04.231+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:59:04.233+0000] {standard_task_runner.py:63} INFO - Started process 6142 to run task
[2024-10-02T18:59:04.234+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-10T00:00:00+00:00', '--job-id', '1255', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmptfb9reeg']
[2024-10-02T18:59:04.238+0000] {standard_task_runner.py:91} INFO - Job 1255: Subtask extrair
[2024-10-02T18:59:04.291+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:59:04.439+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-10T00:00:00+00:00'
[2024-10-02T18:59:04.443+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:59:10.744+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:59:10.745+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:59:10.758+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-10T00:00:00+00:00, execution_date=20240110T000000, start_date=20241002T185903, end_date=20241002T185910
[2024-10-02T18:59:10.826+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:59:10.855+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:59:10.860+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:25:21.447+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:25:21.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [queued]>
[2024-10-02T19:25:21.647+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [queued]>
[2024-10-02T19:25:21.647+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:25:21.711+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-10 00:00:00+00:00
[2024-10-02T19:25:21.717+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9483) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:25:21.719+0000] {standard_task_runner.py:63} INFO - Started process 9500 to run task
[2024-10-02T19:25:21.719+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-10T00:00:00+00:00', '--job-id', '2260', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpm7ydalws']
[2024-10-02T19:25:21.721+0000] {standard_task_runner.py:91} INFO - Job 2260: Subtask extrair
[2024-10-02T19:25:21.769+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-10T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:25:21.863+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-10T00:00:00+00:00'
[2024-10-02T19:25:21.867+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:25:30.036+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:25:30.048+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:25:30.065+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-10T00:00:00+00:00, execution_date=20240110T000000, start_date=20241002T192521, end_date=20241002T192530
[2024-10-02T19:25:30.116+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:25:30.154+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:25:30.157+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
