[2024-10-02T17:25:35.564+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:25:35.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [queued]>
[2024-10-02T17:25:35.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [queued]>
[2024-10-02T17:25:35.606+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:25:35.844+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-10-27 00:00:00+00:00
[2024-10-02T17:25:35.850+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1344) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:25:35.852+0000] {standard_task_runner.py:63} INFO - Started process 1357 to run task
[2024-10-02T17:25:35.851+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-10-27T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpr8umkd2d']
[2024-10-02T17:25:35.853+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask transformar
[2024-10-02T17:25:35.901+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:25:35.981+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-10-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-27T00:00:00+00:00'
[2024-10-02T17:25:35.983+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:25:36.168+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:25:36.169+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in transformar
    df_agrupada = df.groupby('ContinentExp')[['cases', 'deaths']].sum().reset_index()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'ContinentExp'
[2024-10-02T17:25:36.185+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-10-27T00:00:00+00:00, execution_date=20231027T000000, start_date=20241002T172535, end_date=20241002T172536
[2024-10-02T17:25:36.209+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task transformar ('ContinentExp'; 1357)
[2024-10-02T17:25:36.267+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:25:36.293+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:25:36.297+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:57:34.787+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:57:34.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [queued]>
[2024-10-02T18:57:35.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [queued]>
[2024-10-02T18:57:35.044+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:57:35.056+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-10-27 00:00:00+00:00
[2024-10-02T18:57:35.064+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5464) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:57:35.065+0000] {standard_task_runner.py:63} INFO - Started process 5476 to run task
[2024-10-02T18:57:35.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-10-27T00:00:00+00:00', '--job-id', '1040', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp8si_2o_x']
[2024-10-02T18:57:35.067+0000] {standard_task_runner.py:91} INFO - Job 1040: Subtask transformar
[2024-10-02T18:57:35.107+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:57:35.191+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-10-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-27T00:00:00+00:00'
[2024-10-02T18:57:35.196+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:57:35.313+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:57:35.314+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:57:35.321+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-10-27T00:00:00+00:00, execution_date=20231027T000000, start_date=20241002T185734, end_date=20241002T185735
[2024-10-02T18:57:35.359+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:57:35.377+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:57:35.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:23:50.623+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:23:50.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [queued]>
[2024-10-02T19:23:50.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [queued]>
[2024-10-02T19:23:50.813+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:23:50.824+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-10-27 00:00:00+00:00
[2024-10-02T19:23:50.829+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8873) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:23:50.830+0000] {standard_task_runner.py:63} INFO - Started process 8876 to run task
[2024-10-02T19:23:50.830+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-10-27T00:00:00+00:00', '--job-id', '2062', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmppq9x718_']
[2024-10-02T19:23:50.832+0000] {standard_task_runner.py:91} INFO - Job 2062: Subtask transformar
[2024-10-02T19:23:50.875+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-10-27T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:23:50.960+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-10-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-27T00:00:00+00:00'
[2024-10-02T19:23:50.961+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:23:51.098+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:23:51.098+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:23:51.107+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-10-27T00:00:00+00:00, execution_date=20231027T000000, start_date=20241002T192350, end_date=20241002T192351
[2024-10-02T19:23:51.164+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:23:51.189+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:23:51.191+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
