[2024-10-02T17:25:05.785+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:25:05.831+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2024-10-02T17:25:05.854+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2024-10-02T17:25:05.856+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:25:06.187+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2023-10-07 00:00:00+00:00
[2024-10-02T17:25:06.202+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1178) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:25:06.205+0000] {standard_task_runner.py:63} INFO - Started process 1207 to run task
[2024-10-02T17:25:06.205+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2023-10-07T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpgnv9dezw']
[2024-10-02T17:25:06.211+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask extrair
[2024-10-02T17:25:06.298+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:25:06.444+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-07T00:00:00+00:00'
[2024-10-02T17:25:06.446+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:25:13.577+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T17:25:13.577+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:25:13.586+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2023-10-07T00:00:00+00:00, execution_date=20231007T000000, start_date=20241002T172505, end_date=20241002T172513
[2024-10-02T17:25:13.635+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T17:25:13.655+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:25:13.657+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:57:07.411+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:57:07.451+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2024-10-02T18:57:07.460+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2024-10-02T18:57:07.460+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:57:07.743+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2023-10-07 00:00:00+00:00
[2024-10-02T18:57:07.750+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5260) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:57:07.752+0000] {standard_task_runner.py:63} INFO - Started process 5278 to run task
[2024-10-02T18:57:07.752+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2023-10-07T00:00:00+00:00', '--job-id', '974', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp1zr29yd_']
[2024-10-02T18:57:07.755+0000] {standard_task_runner.py:91} INFO - Job 974: Subtask extrair
[2024-10-02T18:57:07.808+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:57:07.907+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-07T00:00:00+00:00'
[2024-10-02T18:57:07.909+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:57:14.051+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:57:14.052+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:57:14.061+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2023-10-07T00:00:00+00:00, execution_date=20231007T000000, start_date=20241002T185707, end_date=20241002T185714
[2024-10-02T18:57:14.099+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:57:14.128+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:57:14.133+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:23:11.880+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:23:11.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2024-10-02T19:23:11.915+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2024-10-02T19:23:11.916+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:23:12.210+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2023-10-07 00:00:00+00:00
[2024-10-02T19:23:12.216+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8717) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:23:12.219+0000] {standard_task_runner.py:63} INFO - Started process 8735 to run task
[2024-10-02T19:23:12.218+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2023-10-07T00:00:00+00:00', '--job-id', '2014', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpd1oedbty']
[2024-10-02T19:23:12.221+0000] {standard_task_runner.py:91} INFO - Job 2014: Subtask extrair
[2024-10-02T19:23:12.275+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2023-10-07T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:23:12.374+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-07T00:00:00+00:00'
[2024-10-02T19:23:12.376+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:23:23.356+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:23:23.357+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in extrair
    df = pd.read_csv(url)
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 377, in _get_filepath_or_buffer
    reader = BytesIO(req.read())
                     ^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 495, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 642, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(2282887 bytes read, 2024415 more expected)
[2024-10-02T19:23:23.369+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2023-10-07T00:00:00+00:00, execution_date=20231007T000000, start_date=20241002T192311, end_date=20241002T192323
[2024-10-02T19:23:23.381+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2014 for task extrair (IncompleteRead(2282887 bytes read, 2024415 more expected); 8735)
[2024-10-02T19:23:23.401+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T19:23:23.419+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:23:23.423+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
