[2024-10-02T17:26:52.983+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:26:53.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-10-02T17:26:53.024+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-10-02T17:26:53.024+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:26:53.041+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-05 00:00:00+00:00
[2024-10-02T17:26:53.050+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1747) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:26:53.052+0000] {standard_task_runner.py:63} INFO - Started process 1760 to run task
[2024-10-02T17:26:53.053+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmptp71bz8n']
[2024-10-02T17:26:53.055+0000] {standard_task_runner.py:91} INFO - Job 192: Subtask extrair
[2024-10-02T17:26:53.343+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:26:53.478+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-10-02T17:26:53.479+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:26:59.640+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:26:59.641+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in extrair
    df.to_csv('data/dados_covid_extraidos.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'
[2024-10-02T17:26:59.653+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-05T00:00:00+00:00, execution_date=20240105T000000, start_date=20241002T172653, end_date=20241002T172659
[2024-10-02T17:26:59.667+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 192 for task extrair ([Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'; 1760)
[2024-10-02T17:26:59.732+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:26:59.757+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:26:59.762+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:58:49.596+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:58:49.616+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-10-02T18:58:49.786+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-10-02T18:58:49.786+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:58:49.799+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-05 00:00:00+00:00
[2024-10-02T18:58:49.804+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6047) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:58:49.805+0000] {standard_task_runner.py:63} INFO - Started process 6055 to run task
[2024-10-02T18:58:49.805+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '1229', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp3kd_c87q']
[2024-10-02T18:58:49.807+0000] {standard_task_runner.py:91} INFO - Job 1229: Subtask extrair
[2024-10-02T18:58:49.845+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:58:49.919+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-10-02T18:58:49.922+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:58:57.384+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:58:57.385+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:58:57.394+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-05T00:00:00+00:00, execution_date=20240105T000000, start_date=20241002T185849, end_date=20241002T185857
[2024-10-02T18:58:57.480+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:58:57.509+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:58:57.512+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:25:20.577+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:25:20.603+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-10-02T19:25:20.798+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [queued]>
[2024-10-02T19:25:20.799+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:25:20.834+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-05 00:00:00+00:00
[2024-10-02T19:25:20.843+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9470) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:25:20.844+0000] {standard_task_runner.py:63} INFO - Started process 9486 to run task
[2024-10-02T19:25:20.845+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-05T00:00:00+00:00', '--job-id', '2255', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpgsbai4js']
[2024-10-02T19:25:20.847+0000] {standard_task_runner.py:91} INFO - Job 2255: Subtask extrair
[2024-10-02T19:25:20.916+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-05T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:25:21.011+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T00:00:00+00:00'
[2024-10-02T19:25:21.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:25:27.800+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:25:27.801+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:25:27.818+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-05T00:00:00+00:00, execution_date=20240105T000000, start_date=20241002T192520, end_date=20241002T192527
[2024-10-02T19:25:27.870+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:25:27.918+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:25:27.922+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
