[2024-10-02T17:27:08.960+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:27:08.982+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-10-02T17:27:08.989+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-10-02T17:27:08.989+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:27:09.161+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-02-02 00:00:00+00:00
[2024-10-02T17:27:09.168+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1830) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:27:09.169+0000] {standard_task_runner.py:63} INFO - Started process 1838 to run task
[2024-10-02T17:27:09.169+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp271nrrq2']
[2024-10-02T17:27:09.171+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask extrair
[2024-10-02T17:27:09.207+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:27:09.278+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-10-02T17:27:09.279+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:27:15.060+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:27:15.061+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in extrair
    df.to_csv('data/dados_covid_extraidos.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'
[2024-10-02T17:27:15.073+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-02-02T00:00:00+00:00, execution_date=20240202T000000, start_date=20241002T172708, end_date=20241002T172715
[2024-10-02T17:27:15.083+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 220 for task extrair ([Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'; 1838)
[2024-10-02T17:27:15.114+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:27:15.132+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:27:15.137+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:59:39.796+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:59:39.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-10-02T18:59:40.113+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-10-02T18:59:40.116+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:59:40.156+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-02-02 00:00:00+00:00
[2024-10-02T18:59:40.164+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6330) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:59:40.167+0000] {standard_task_runner.py:63} INFO - Started process 6348 to run task
[2024-10-02T18:59:40.167+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '1320', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpeb2qaaiv']
[2024-10-02T18:59:40.176+0000] {standard_task_runner.py:91} INFO - Job 1320: Subtask extrair
[2024-10-02T18:59:40.260+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:59:40.424+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-10-02T18:59:40.433+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:59:46.016+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:59:46.016+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:59:46.025+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-02-02T00:00:00+00:00, execution_date=20240202T000000, start_date=20241002T185939, end_date=20241002T185946
[2024-10-02T18:59:46.064+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:59:46.082+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:59:46.084+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:25:53.231+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:25:53.409+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-10-02T19:25:53.416+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-10-02T19:25:53.417+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:25:53.431+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-02-02 00:00:00+00:00
[2024-10-02T19:25:53.437+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9755) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:25:53.439+0000] {standard_task_runner.py:63} INFO - Started process 9757 to run task
[2024-10-02T19:25:53.439+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '2346', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp_2sriyi2']
[2024-10-02T19:25:53.440+0000] {standard_task_runner.py:91} INFO - Job 2346: Subtask extrair
[2024-10-02T19:25:53.476+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-02-02T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:25:53.552+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-10-02T19:25:53.553+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:25:58.825+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:25:58.826+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:25:58.833+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-02-02T00:00:00+00:00, execution_date=20240202T000000, start_date=20241002T192553, end_date=20241002T192558
[2024-10-02T19:25:58.861+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:25:58.879+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:25:58.881+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
