[2024-10-02T17:26:33.547+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:26:33.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2024-10-02T17:26:33.578+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2024-10-02T17:26:33.579+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:26:33.595+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-12-13 00:00:00+00:00
[2024-10-02T17:26:33.603+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1638) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:26:33.605+0000] {standard_task_runner.py:63} INFO - Started process 1643 to run task
[2024-10-02T17:26:33.605+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-12-13T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmppicr1zts']
[2024-10-02T17:26:33.607+0000] {standard_task_runner.py:91} INFO - Job 156: Subtask transformar
[2024-10-02T17:26:33.854+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:26:33.920+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-13T00:00:00+00:00'
[2024-10-02T17:26:33.921+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:26:34.048+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:26:34.049+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in transformar
    df_agrupada = df.groupby('ContinentExp')[['cases', 'deaths']].sum().reset_index()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'ContinentExp'
[2024-10-02T17:26:34.061+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-12-13T00:00:00+00:00, execution_date=20231213T000000, start_date=20241002T172633, end_date=20241002T172634
[2024-10-02T17:26:34.071+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 156 for task transformar ('ContinentExp'; 1643)
[2024-10-02T17:26:34.099+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:26:34.306+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:26:34.311+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:58:35.689+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:58:35.729+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2024-10-02T18:58:36.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2024-10-02T18:58:36.014+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:58:36.035+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-12-13 00:00:00+00:00
[2024-10-02T18:58:36.047+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5916) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:58:36.049+0000] {standard_task_runner.py:63} INFO - Started process 5938 to run task
[2024-10-02T18:58:36.048+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-12-13T00:00:00+00:00', '--job-id', '1185', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpc32ke5zl']
[2024-10-02T18:58:36.051+0000] {standard_task_runner.py:91} INFO - Job 1185: Subtask transformar
[2024-10-02T18:58:36.119+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:58:36.255+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-13T00:00:00+00:00'
[2024-10-02T18:58:36.262+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:58:36.407+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:58:36.408+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:58:36.419+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-12-13T00:00:00+00:00, execution_date=20231213T000000, start_date=20241002T185835, end_date=20241002T185836
[2024-10-02T18:58:36.544+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:58:36.573+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:58:36.577+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:24:54.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:24:54.779+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2024-10-02T19:24:55.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2024-10-02T19:24:55.115+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:24:55.148+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-12-13 00:00:00+00:00
[2024-10-02T19:24:55.160+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9295) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:24:55.162+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-12-13T00:00:00+00:00', '--job-id', '2199', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpidhyy23s']
[2024-10-02T19:24:55.163+0000] {standard_task_runner.py:63} INFO - Started process 9320 to run task
[2024-10-02T19:24:55.164+0000] {standard_task_runner.py:91} INFO - Job 2199: Subtask transformar
[2024-10-02T19:24:55.264+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-13T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:24:55.437+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-13T00:00:00+00:00'
[2024-10-02T19:24:55.445+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:24:55.778+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:24:55.791+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:24:55.818+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-12-13T00:00:00+00:00, execution_date=20231213T000000, start_date=20241002T192454, end_date=20241002T192455
[2024-10-02T19:24:55.916+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:24:55.983+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:24:55.999+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
