[2024-10-02T17:25:50.623+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:25:50.650+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2024-10-02T17:25:50.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2024-10-02T17:25:50.659+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:25:50.869+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-04 00:00:00+00:00
[2024-10-02T17:25:50.875+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1427) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:25:50.876+0000] {standard_task_runner.py:63} INFO - Started process 1433 to run task
[2024-10-02T17:25:50.876+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpepg5o_5d']
[2024-10-02T17:25:50.878+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask transformar
[2024-10-02T17:25:50.923+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:25:50.998+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2024-10-02T17:25:51.000+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:25:51.130+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:25:51.132+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in transformar
    df_agrupada = df.groupby('ContinentExp')[['cases', 'deaths']].sum().reset_index()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'ContinentExp'
[2024-10-02T17:25:51.149+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-04T00:00:00+00:00, execution_date=20231104T000000, start_date=20241002T172550, end_date=20241002T172551
[2024-10-02T17:25:51.164+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task transformar ('ContinentExp'; 1433)
[2024-10-02T17:25:51.210+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:25:51.235+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:25:51.239+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:57:51.580+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:57:51.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2024-10-02T18:57:51.624+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2024-10-02T18:57:51.627+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:57:51.982+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-04 00:00:00+00:00
[2024-10-02T18:57:51.996+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5597) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:57:51.998+0000] {standard_task_runner.py:63} INFO - Started process 5624 to run task
[2024-10-02T18:57:51.998+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '1084', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpc8v8pjl5']
[2024-10-02T18:57:52.002+0000] {standard_task_runner.py:91} INFO - Job 1084: Subtask transformar
[2024-10-02T18:57:52.083+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:57:52.227+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2024-10-02T18:57:52.229+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:57:52.472+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:57:52.474+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:57:52.486+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-04T00:00:00+00:00, execution_date=20231104T000000, start_date=20241002T185751, end_date=20241002T185752
[2024-10-02T18:57:52.540+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:57:52.574+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:57:52.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:24:09.064+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:24:09.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2024-10-02T19:24:09.373+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [queued]>
[2024-10-02T19:24:09.374+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:24:09.392+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-11-04 00:00:00+00:00
[2024-10-02T19:24:09.404+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8976) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:24:09.406+0000] {standard_task_runner.py:63} INFO - Started process 8993 to run task
[2024-10-02T19:24:09.405+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-11-04T00:00:00+00:00', '--job-id', '2095', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp3xuwy5o9']
[2024-10-02T19:24:09.408+0000] {standard_task_runner.py:91} INFO - Job 2095: Subtask transformar
[2024-10-02T19:24:09.470+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-11-04T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:24:09.617+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-04T00:00:00+00:00'
[2024-10-02T19:24:09.619+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:24:09.724+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:24:09.725+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:24:09.737+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-11-04T00:00:00+00:00, execution_date=20231104T000000, start_date=20241002T192409, end_date=20241002T192409
[2024-10-02T19:24:09.783+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:24:09.809+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:24:09.813+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
