[2024-10-02T17:27:07.169+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:27:07.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-10-02T17:27:07.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-10-02T17:27:07.203+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:27:07.488+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-24 00:00:00+00:00
[2024-10-02T17:27:07.495+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1802) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:27:07.496+0000] {standard_task_runner.py:63} INFO - Started process 1819 to run task
[2024-10-02T17:27:07.496+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-24T00:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp1g3mfsfi']
[2024-10-02T17:27:07.498+0000] {standard_task_runner.py:91} INFO - Job 211: Subtask extrair
[2024-10-02T17:27:07.541+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:27:07.636+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-24T00:00:00+00:00'
[2024-10-02T17:27:07.637+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:27:14.221+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:27:14.222+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in extrair
    df.to_csv('data/dados_covid_extraidos.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'
[2024-10-02T17:27:14.233+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-24T00:00:00+00:00, execution_date=20240124T000000, start_date=20241002T172707, end_date=20241002T172714
[2024-10-02T17:27:14.243+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 211 for task extrair ([Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'; 1819)
[2024-10-02T17:27:14.284+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:27:14.309+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:27:14.313+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:59:19.386+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:59:19.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-10-02T18:59:19.597+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-10-02T18:59:19.597+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:59:19.611+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-24 00:00:00+00:00
[2024-10-02T18:59:19.619+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6260) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:59:19.620+0000] {standard_task_runner.py:63} INFO - Started process 6268 to run task
[2024-10-02T18:59:19.620+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-24T00:00:00+00:00', '--job-id', '1297', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp6ptyfuuv']
[2024-10-02T18:59:19.622+0000] {standard_task_runner.py:91} INFO - Job 1297: Subtask extrair
[2024-10-02T18:59:19.660+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:59:19.740+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-24T00:00:00+00:00'
[2024-10-02T18:59:19.742+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:59:29.344+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:59:29.345+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:59:29.351+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-24T00:00:00+00:00, execution_date=20240124T000000, start_date=20241002T185919, end_date=20241002T185929
[2024-10-02T18:59:29.370+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:59:29.389+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:59:29.391+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:25:38.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:25:38.620+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-10-02T19:25:38.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [queued]>
[2024-10-02T19:25:38.811+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:25:38.825+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-24 00:00:00+00:00
[2024-10-02T19:25:38.833+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9620) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:25:38.834+0000] {standard_task_runner.py:63} INFO - Started process 9638 to run task
[2024-10-02T19:25:38.834+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-24T00:00:00+00:00', '--job-id', '2306', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpd0_4eztr']
[2024-10-02T19:25:38.836+0000] {standard_task_runner.py:91} INFO - Job 2306: Subtask extrair
[2024-10-02T19:25:38.883+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-24T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:25:38.978+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-24T00:00:00+00:00'
[2024-10-02T19:25:38.981+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:25:43.914+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:25:43.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:25:43.922+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-24T00:00:00+00:00, execution_date=20240124T000000, start_date=20241002T192538, end_date=20241002T192543
[2024-10-02T19:25:43.977+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:25:44.001+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:25:44.003+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
