[2024-10-02T17:26:33.549+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:26:33.573+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2024-10-02T17:26:33.580+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2024-10-02T17:26:33.581+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:26:33.776+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-12-18 00:00:00+00:00
[2024-10-02T17:26:33.782+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1637) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:26:33.783+0000] {standard_task_runner.py:63} INFO - Started process 1644 to run task
[2024-10-02T17:26:33.783+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-12-18T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpmjyhx43m']
[2024-10-02T17:26:33.786+0000] {standard_task_runner.py:91} INFO - Job 158: Subtask transformar
[2024-10-02T17:26:33.833+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:26:33.907+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-18T00:00:00+00:00'
[2024-10-02T17:26:33.908+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:26:34.052+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:26:34.052+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 17, in transformar
    df_agrupada = df.groupby('ContinentExp')[['cases', 'deaths']].sum().reset_index()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'ContinentExp'
[2024-10-02T17:26:34.062+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-12-18T00:00:00+00:00, execution_date=20231218T000000, start_date=20241002T172633, end_date=20241002T172634
[2024-10-02T17:26:34.074+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 158 for task transformar ('ContinentExp'; 1644)
[2024-10-02T17:26:34.117+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:26:34.125+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:58:38.605+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:58:38.632+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2024-10-02T18:58:38.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2024-10-02T18:58:38.900+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:58:38.918+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-12-18 00:00:00+00:00
[2024-10-02T18:58:38.928+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5958) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:58:38.933+0000] {standard_task_runner.py:63} INFO - Started process 5974 to run task
[2024-10-02T18:58:38.935+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-12-18T00:00:00+00:00', '--job-id', '1195', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpecjzupq5']
[2024-10-02T18:58:38.938+0000] {standard_task_runner.py:91} INFO - Job 1195: Subtask transformar
[2024-10-02T18:58:38.997+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:58:39.114+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-18T00:00:00+00:00'
[2024-10-02T18:58:39.118+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:58:39.323+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:58:39.324+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:58:39.336+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-12-18T00:00:00+00:00, execution_date=20231218T000000, start_date=20241002T185838, end_date=20241002T185839
[2024-10-02T18:58:39.470+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:58:39.493+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:58:39.496+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:24:56.679+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:24:56.718+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2024-10-02T19:24:56.908+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2024-10-02T19:24:56.908+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:24:56.920+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar> on 2023-12-18 00:00:00+00:00
[2024-10-02T19:24:56.928+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9326) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:24:56.929+0000] {standard_task_runner.py:63} INFO - Started process 9338 to run task
[2024-10-02T19:24:56.929+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'transformar', 'scheduled__2023-12-18T00:00:00+00:00', '--job-id', '2211', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmplz022hkm']
[2024-10-02T19:24:56.931+0000] {standard_task_runner.py:91} INFO - Job 2211: Subtask transformar
[2024-10-02T19:24:56.972+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.transformar scheduled__2023-12-18T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:24:57.062+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='transformar' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-18T00:00:00+00:00'
[2024-10-02T19:24:57.065+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:24:57.267+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:24:57.268+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:24:57.281+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=transformar, run_id=scheduled__2023-12-18T00:00:00+00:00, execution_date=20231218T000000, start_date=20241002T192456, end_date=20241002T192457
[2024-10-02T19:24:57.344+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:24:57.355+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
