[2024-10-02T17:26:53.122+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T17:26:53.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-10-02T17:26:53.158+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-10-02T17:26:53.159+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T17:26:53.382+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-06 00:00:00+00:00
[2024-10-02T17:26:53.391+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1749) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T17:26:53.393+0000] {standard_task_runner.py:63} INFO - Started process 1764 to run task
[2024-10-02T17:26:53.393+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmplu6bq8oh']
[2024-10-02T17:26:53.395+0000] {standard_task_runner.py:91} INFO - Job 193: Subtask extrair
[2024-10-02T17:26:53.492+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T17:26:53.625+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-10-02T17:26:53.626+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T17:26:59.667+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T17:26:59.668+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in extrair
    df.to_csv('data/dados_covid_extraidos.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'
[2024-10-02T17:26:59.683+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-06T00:00:00+00:00, execution_date=20240106T000000, start_date=20241002T172653, end_date=20241002T172659
[2024-10-02T17:26:59.700+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 193 for task extrair ([Errno 13] Permission denied: 'data/dados_covid_extraidos.csv'; 1764)
[2024-10-02T17:26:59.743+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-02T17:26:59.767+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-02T17:26:59.772+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T18:59:03.243+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T18:59:03.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-10-02T18:59:03.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-10-02T18:59:03.507+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T18:59:03.525+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-06 00:00:00+00:00
[2024-10-02T18:59:03.534+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T18:59:03.536+0000] {standard_task_runner.py:63} INFO - Started process 6133 to run task
[2024-10-02T18:59:03.536+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '1251', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp3wvekxwn']
[2024-10-02T18:59:03.538+0000] {standard_task_runner.py:91} INFO - Job 1251: Subtask extrair
[2024-10-02T18:59:03.589+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T18:59:03.710+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-10-02T18:59:03.714+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T18:59:14.530+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T18:59:14.531+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T18:59:14.548+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-06T00:00:00+00:00, execution_date=20240106T000000, start_date=20241002T185903, end_date=20241002T185914
[2024-10-02T18:59:14.607+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T18:59:14.648+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T18:59:14.652+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-02T19:25:20.732+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-02T19:25:20.760+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-10-02T19:25:20.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-10-02T19:25:20.971+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-02T19:25:21.061+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extrair> on 2024-01-06 00:00:00+00:00
[2024-10-02T19:25:21.068+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9472) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T19:25:21.069+0000] {standard_task_runner.py:63} INFO - Started process 9489 to run task
[2024-10-02T19:25:21.069+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_covid_europa_pipeline', 'extrair', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '2256', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp730v6np5']
[2024-10-02T19:25:21.071+0000] {standard_task_runner.py:91} INFO - Job 2256: Subtask extrair
[2024-10-02T19:25:21.117+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_covid_europa_pipeline.extrair scheduled__2024-01-06T00:00:00+00:00 [running]> on host 99de7dfc3871
[2024-10-02T19:25:21.216+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_covid_europa_pipeline' AIRFLOW_CTX_TASK_ID='extrair' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-10-02T19:25:21.219+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-02T19:25:26.691+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-02T19:25:26.692+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-02T19:25:26.701+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_covid_europa_pipeline, task_id=extrair, run_id=scheduled__2024-01-06T00:00:00+00:00, execution_date=20240106T000000, start_date=20241002T192520, end_date=20241002T192526
[2024-10-02T19:25:26.733+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-02T19:25:26.758+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T19:25:26.765+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
